version: "3.8"

services:
  backend:
    image: lijons/nova-backend
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017/brix
      - PEERJS_URL=http://peerjs:5000
    depends_on:
      - mongo
      - peerjs
    restart: unless-stopped

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=yourdb
    restart: unless-stopped

  peerjs:
    image: peerjs/peerjs-server
    ports:
      - "5000:5000"
    command: ["peerjs", "--port", "5000", "--path", "/peerjs"] # ✅ Required!
    restart: unless-stopped
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - backend
    restart: unless-stopped
  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: >
      sh -c "sleep 15 && certbot certonly --webroot --webroot-path=/var/www/certbot \
      --email lijons13@gmail.com --agree-tos --no-eff-email -d apinova.ddns.net"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  mongo_data:
