import { Types } from "mongoose";

export interface IMessage {
  _id?: Types.ObjectId; // optional because MongoDB assigns it
  sender: Types.ObjectId; // reference to User
  receiver: Types.ObjectId; // reference to User
  content: string;
  isRead: boolean;
  createdAt?: Date; // auto-generated by timestamps
  updatedAt?: Date; // auto-generated by timestamps
}
