export const IndustryTypes = [
  "Information Technology",
  "Software Development",
  "E-Commerce",
  "Banking & Financial Services",
  "Healthcare",
  "Pharmaceutical",
  "Telecommunications",
  "Education & Training",
  "Manufacturing",
  "Automotive",
  "Construction",
  "Retail",
  "Logistics & Supply Chain",
  "Media & Entertainment",
  "Hospitality",
  "Real Estate",
  "Legal Services",
  "Agriculture",
  "Energy & Utilities",
  "Non-Profit / NGO",
  "Government / Public Administration",
  "Consulting",
  "Human Resources",
  "Marketing & Advertising",
  "Insurance",
  "Aviation / Aerospace",
  "Chemicals",
  "Fashion & Apparel",
  "Mining & Metals",
  "Sports & Fitness",
  "Food & Beverage",
  "Maritime",
  "Defense & Security",
  "Electronics / Electrical",
  "Environmental Services",
  "Research & Development",
  "Arts & Culture",
];
